/*
 * SPDX-License-Identifier: Apache-2.0
 */

//===------------------------ MQCompilerOptions.hpp ---------------------===//
//
// Copyright 2026-2029 Li Fan.
//
// =============================================================================
//
//
//===----------------------------------------------------------------------===//

#ifndef ONNX_MLIR_MQ_COMPILER_OPTIONS_H
#define ONNX_MLIR_MQ_COMPILER_OPTIONS_H

#include "llvm/Support/CommandLine.h"

// clang-format off

#define INSTRUMENTSTAGE_ENUM_MQ                                               \
    ,                                                                          \
    ZHigh,                                                                     \
    ZLow

// clang-format on

#define INSTRUMENTSTAGE_CL_ENUM_MQ                                           \
  clEnumVal(Onnx, "Profile for onnx ops. For MQ, profile onnx ops before "   \
                  "lowering to zhigh."),                                       \
      clEnumVal(ZHigh, "MQ profiling for onnx and zhigh ops."),              \
      clEnumVal(ZLow, "MQ profiling for zlow ops.")

#define PROFILEIR_CL_ENUM_MQ                                                 \
  , clEnumVal(ZHigh, "Profile operations in ZHighIR generated by "             \
                     "--EmitZHighIR.")

#define OPTREPORT_ENUM_MQ , MQUnsupportedOps

#define OPTREPORT_CL_ENUM_MQ                                                 \
  , clEnumVal(MQUnsupportedOps,                                              \
        "Provide report on why ONNX ops did not run on MQ.")

namespace onnx_mlir {
// typedef enum {
//   EmitZNONE,
//   EmitZLowIR,
//   EmitZHighIR,
// } MQEmissionTargetType;

// typedef enum {
//   QualifyingOps,    /* Any ops that qualify for MQ will go on MQ. */
//   FasterOps,        /* Only qualifying ops that are faster on MQ */
//   FasterOpsWSU,     /* FasterOps with With Stick and Unstick (WSU) cost.*/
//   MuchFasterOpsWSU, /* FasterOpsWSU only if significantly faster. */
// } MQPlacementHeuristic;

// // Quantization type
// typedef enum {
//   symWeight,
//   asymWeight,
//   symActivation,
//   asymActivation,
//   autoQuantOpt,
// } MQQuantOptions;

extern llvm::cl::OptionCategory OnnxMlirOptions;
extern llvm::cl::OptionCategory OnnxMlirCommonOptions;
// extern llvm::cl::opt<onnx_mlir::MQEmissionTargetType> MQEmissionTarget;
// extern llvm::cl::opt<bool> MQDisableZHighToOnnx;
// extern llvm::cl::opt<bool> MQDisableZHighDecomposeStickUnstick;
// extern llvm::cl::opt<bool> MQDisableCompilerStickUnstick;
// extern llvm::cl::opt<bool> MQEnableScalarBcastBinary;
// extern llvm::cl::opt<MQPlacementHeuristic> MQPlacementHeuristic;
// extern llvm::cl::opt<bool> profileZHighIR;
// extern llvm::cl::opt<std::string> MQLoadConfigFile;
// extern llvm::cl::opt<std::string> MQSaveConfigFile;
// extern llvm::cl::opt<bool> MQDisableSaturation;
// extern llvm::cl::opt<bool> MQUseDynamicQuantizeLinearOnCPU;
// extern llvm::cl::opt<bool> MQUseDynamicQuantizeLinearOnCPUForScaleOffset;
// extern llvm::cl::opt<bool> MQDisableFusionOpStickUnstick;
// extern std::vector<MQQuantOptions> MQQuantDynamic;
// extern std::vector<std::string> MQQuantOpTypes;

} // namespace onnx_mlir
#endif
